### ISSUE TITLE
Premium demo not working

### ISSUE THREAD

**Issue by shinokada** [pisyek/room-booking-system#2]
Hi I logged in https://demo.pisyek.com/room-pro/dashboard but it gives an error.

![screen shot 2017-05-30 at 6 22 04 pm](https://cloud.githubusercontent.com/assets/147320/26576769/0c22a584-4565-11e7-9095-36fffbae17e6.png)

**Comment by pisyek** [comment]
Hi shinokada

Kindly retry as i fixed the problem. Turn out that i got problem with db.

You should be able to view the dashboard.

![lrbs](https://cloud.githubusercontent.com/assets/10695986/26588172/1d7b93c8-4587-11e7-8d5c-ae8e9f048640.PNG)
