### ISSUE TITLE
Installing system

### ISSUE THREAD

**Issue by buckl97** [pisyek/room-booking-system#3]
Hi there,

I cannot navigate through the tutorial on your website. It there a payment required to do this?

**Comment by pisyek** [comment]
TLDR:

For installation, just duplicate this repo, do composer install, and run migration and seed. That's it.

@buckl97 The tutorial is free and you can navigate the pages using the pagination button at the end of the blog post.

**Screenshot:**
![pages](https://user-images.githubusercontent.com/10695986/48381470-ed388080-e716-11e8-9ac8-85ab43de24f3.PNG)
